# Generated by Django 4.2.4 on 2023-11-23 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='installmentsProducts',
        ),
    ]
