# Generated by Django 4.2.4 on 2023-11-20 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0002_installmentsproducts_depositoptions_dcls_month_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='installmentsOptions',
        ),
    ]
